name: "Credly Badges"

on:
  schedule:
    - cron: "0 0 2 * *"

jobs:
  credly-badges:
    name: "Update README with Credly badges"
    runs-on: ubuntu-latest

    steps:
      - name: Update
        uses: mikejoh/credly-badges@main
        with:
          CREDLY_USERNAME: pierre-louis-gueugnon
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: "Update Credly badges!"
