name: "Credly Badges"

#on:
#  schedule:
#    - cron: "0 0 2 * *"

on:
  push:

jobs:
  credly-badges:
    name: "Update README with Credly badges"
    runs-on: ubuntu-latest
    permissions: 
      contents: write

    steps:
      - name: Update badges
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: pierre-louis-gueugnon
          COMMIT_MESSAGE: "Update Credly badges!"
